### ISSUE TITLE
Sits on HTC screen

### ISSUE THREAD

**Issue by zoe-vb** [WolfLink115/UbuntuTouchHTCOneM7#1]
Hello, I've flashed the boot image and used halium-install and yet the device boots into a HTC screen and no RNDIS device shows up.

**Comment by WolfLink115** [comment]
Sorry for the severely late reply, been all over the place-

I have made an attempt to fix that, seems like it might be the rootfs used. The halium-boot.img and system.img built here was meant for Ubuntu Touch 16.04 and for some reason I couldn't seem to build it for 20.04. I tried asking for assistance in the Ubuntu Touch Porting group but no one seemed to be able to help out, was mostly ignored to be honest. Anyways I might try again later on down the line, I need to get a new HDD for that first though. Anyways, I wish you the best of luck!
